// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PortCDM {
	
	
	public partial class NewPortCDMMessage {
		
		protected System.Web.UI.WebControls.Content MessageContent;
		
		protected System.Web.UI.WebControls.Literal vesselId;

	    protected System.Web.UI.WebControls.Literal messageId;
		
		protected System.Web.UI.WebControls.Literal locationStateId;
		
		protected System.Web.UI.WebControls.Literal timeType;
		
		protected System.Web.UI.WebControls.Literal time;
		
		protected System.Web.UI.WebControls.Literal locationType;
		
		protected System.Web.UI.WebControls.Literal latitude;
		
		protected System.Web.UI.WebControls.Literal longitude;
		
		protected System.Web.UI.WebControls.Literal positionType;
		
		protected System.Web.UI.WebControls.Button sendMessageButton;
		
		protected System.Web.UI.WebControls.Literal messageConfirmationLiteral;
	}
}
