// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PortCDM {
	
	
	public partial class FrontEnd {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cpMainContent;
	}
}
