// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PortCDM {
	
	
	public partial class Ships {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.UpdatePanel updatePanelAdd;
		
		protected System.Web.UI.WebControls.DropDownList addShipDropDown;
		
		protected System.Web.UI.WebControls.Button addShipButton;
		
		protected System.Web.UI.UpdatePanel updatePanel;
		
		protected System.Web.UI.WebControls.Repeater shipRepeater;
		
		protected System.Web.UI.WebControls.Literal imo;
	}
}
