
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortCDM {
    
    
    public partial class Timeline {

        protected System.Web.UI.WebControls.Content Content1;

        protected System.Web.UI.WebControls.Literal eventId;

        protected System.Web.UI.WebControls.Repeater eventListBox;

        protected System.Web.UI.WebControls.Literal atOrFrom;
    }
}

