//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17", IsNullable=false)]
public partial class portCallMessage {
    
    private string portCallIdField;
    
    private string localPortCallIdField;
    
    private string localJobIdField;
    
    private string vesselIdField;
    
    private string messageIdField;
    
    private string groupWithField;
    
    private System.DateTime reportedAtField;
    
    private bool reportedAtFieldSpecified;
    
    private string reportedByField;
    
    private string commentField;
    
    private object itemField;
    
    /// <remarks/>
    public string portCallId {
        get {
            return this.portCallIdField;
        }
        set {
            this.portCallIdField = value;
        }
    }
    
    /// <remarks/>
    public string localPortCallId {
        get {
            return this.localPortCallIdField;
        }
        set {
            this.localPortCallIdField = value;
        }
    }
    
    /// <remarks/>
    public string localJobId {
        get {
            return this.localJobIdField;
        }
        set {
            this.localJobIdField = value;
        }
    }
    
    /// <remarks/>
    public string vesselId {
        get {
            return this.vesselIdField;
        }
        set {
            this.vesselIdField = value;
        }
    }
    
    /// <remarks/>
    public string messageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
    
    /// <remarks/>
    public string groupWith {
        get {
            return this.groupWithField;
        }
        set {
            this.groupWithField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime reportedAt {
        get {
            return this.reportedAtField;
        }
        set {
            this.reportedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool reportedAtSpecified {
        get {
            return this.reportedAtFieldSpecified;
        }
        set {
            this.reportedAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string reportedBy {
        get {
            return this.reportedByField;
        }
        set {
            this.reportedByField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("locationState", typeof(LocationState))]
    [System.Xml.Serialization.XmlElementAttribute("messageOperation", typeof(MessageOperation))]
    [System.Xml.Serialization.XmlElementAttribute("serviceState", typeof(ServiceState))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class LocationState {
    
    private LocationReferenceObject referenceObjectField;
    
    private System.DateTime timeField;
    
    private TimeType timeTypeField;
    
    private object itemField;
    
    /// <remarks/>
    public LocationReferenceObject referenceObject {
        get {
            return this.referenceObjectField;
        }
        set {
            this.referenceObjectField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public TimeType timeType {
        get {
            return this.timeTypeField;
        }
        set {
            this.timeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arrivalLocation", typeof(LocationStateArrivalLocation))]
    [System.Xml.Serialization.XmlElementAttribute("departureLocation", typeof(LocationStateDepartureLocation))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum LocationReferenceObject {
    
    /// <remarks/>
    VESSEL,
    
    /// <remarks/>
    TUG,
    
    /// <remarks/>
    ESCORT_TUG,
    
    /// <remarks/>
    PILOT,
    
    /// <remarks/>
    PILOT_BOAT,
    
    /// <remarks/>
    ICEBREAKER,
    
    /// <remarks/>
    AGENT,
    
    /// <remarks/>
    ARRIVAL_MOORER,
    
    /// <remarks/>
    DEPARTURE_MOORER,
    
    /// <remarks/>
    PASSENGER,
    
    /// <remarks/>
    SECURITY,
    
    /// <remarks/>
    PONTOONS_AND_FENDERS,
    
    /// <remarks/>
    BUNKER_VESSEL,
    
    /// <remarks/>
    SLUDGE_VESSEL,
    
    /// <remarks/>
    SLOP_VESSEL,
    
    /// <remarks/>
    FRESH_WATER_VESSEL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum TimeType {
    
    /// <remarks/>
    ESTIMATED,
    
    /// <remarks/>
    ACTUAL,
    
    /// <remarks/>
    TARGET,
    
    /// <remarks/>
    RECOMMENDED,
    
    /// <remarks/>
    CANCELLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class LocationStateArrivalLocation {
    
    private Location fromField;
    
    private Location toField;
    
    /// <remarks/>
    public Location from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public Location to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class Location {
    
    private LogicalLocation locationTypeField;
    
    private Position positionField;
    
    private string nameField;
    
    /// <remarks/>
    public LogicalLocation locationType {
        get {
            return this.locationTypeField;
        }
        set {
            this.locationTypeField = value;
        }
    }
    
    /// <remarks/>
    public Position position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum LogicalLocation {
    
    /// <remarks/>
    ANCHORING_AREA,
    
    /// <remarks/>
    BERTH,
    
    /// <remarks/>
    ETUG_ZONE,
    
    /// <remarks/>
    LOC,
    
    /// <remarks/>
    PILOT_BOARDING_AREA,
    
    /// <remarks/>
    RENDEZV_AREA,
    
    /// <remarks/>
    TRAFFIC_AREA,
    
    /// <remarks/>
    TUG_ZONE,
    
    /// <remarks/>
    VESSEL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class Position {
    
    private double latitudeField;
    
    private double longitudeField;
    
    /// <remarks/>
    public double latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public double longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class ServiceState {
    
    private ServiceObject serviceObjectField;
    
    private string performingActorField;
    
    private ServiceTimeSequence timeSequenceField;
    
    private System.DateTime timeField;
    
    private TimeType timeTypeField;
    
    private object itemField;
    
    /// <remarks/>
    public ServiceObject serviceObject {
        get {
            return this.serviceObjectField;
        }
        set {
            this.serviceObjectField = value;
        }
    }
    
    /// <remarks/>
    public string performingActor {
        get {
            return this.performingActorField;
        }
        set {
            this.performingActorField = value;
        }
    }
    
    /// <remarks/>
    public ServiceTimeSequence timeSequence {
        get {
            return this.timeSequenceField;
        }
        set {
            this.timeSequenceField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public TimeType timeType {
        get {
            return this.timeTypeField;
        }
        set {
            this.timeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("at", typeof(Location))]
    [System.Xml.Serialization.XmlElementAttribute("between", typeof(ServiceStateBetween))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum ServiceObject {
    
    /// <remarks/>
    ANCHORING,
    
    /// <remarks/>
    ARRIVAL_ANCHORING_OPERATION,
    
    /// <remarks/>
    ARRIVAL_BERTH,
    
    /// <remarks/>
    ARRIVAL_PORTAREA,
    
    /// <remarks/>
    ARRIVAL_VTSAREA,
    
    /// <remarks/>
    BERTH_SHIFTING,
    
    /// <remarks/>
    BUNKERING_OPERATION,
    
    /// <remarks/>
    CARGO_OPERATION,
    
    /// <remarks/>
    DEPARTURE_ANCHORING_OPERATION,
    
    /// <remarks/>
    DEPARTURE_BERTH,
    
    /// <remarks/>
    DEPARTURE_PORTAREA,
    
    /// <remarks/>
    DEPARTURE_VTSAREA,
    
    /// <remarks/>
    ESCORT_TOWAGE,
    
    /// <remarks/>
    GARBAGE_OPERATION,
    
    /// <remarks/>
    ICEBREAKING_OPERATION,
    
    /// <remarks/>
    LUBEOIL_OPERATION,
    
    /// <remarks/>
    ARRIVAL_MOORING_OPERATION,
    
    /// <remarks/>
    DEPARTURE_MOORING_OPERATION,
    
    /// <remarks/>
    PILOTAGE,
    
    /// <remarks/>
    POSTCARGOSURVEY,
    
    /// <remarks/>
    PRECARGOSURVEY,
    
    /// <remarks/>
    PROVISION_OPERATION,
    
    /// <remarks/>
    SLOP_OPERATION,
    
    /// <remarks/>
    SLUDGE_OPERATION,
    
    /// <remarks/>
    TOWAGE,
    
    /// <remarks/>
    WATER_OPERATION,
    
    /// <remarks/>
    GANGWAY,
    
    /// <remarks/>
    EMBARKING,
    
    /// <remarks/>
    PILOT_BOAT,
    
    /// <remarks/>
    PONTOONS_AND_FENDERS,
    
    /// <remarks/>
    SECURITY,
    
    /// <remarks/>
    TOURS,
    
    /// <remarks/>
    FORKLIFT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum ServiceTimeSequence {
    
    /// <remarks/>
    COMMENCED,
    
    /// <remarks/>
    COMPLETED,
    
    /// <remarks/>
    CONFIRMED,
    
    /// <remarks/>
    DENIED,
    
    /// <remarks/>
    REQUESTED,
    
    /// <remarks/>
    REQUEST_RECEIVED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class ServiceStateBetween {
    
    private Location toField;
    
    private Location fromField;
    
    /// <remarks/>
    public Location to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    public Location from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class MessageOperation {
    
    private MessageOperationOperation operationField;
    
    private string messageIdField;
    
    /// <remarks/>
    public MessageOperationOperation operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    public string messageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public enum MessageOperationOperation {
    
    /// <remarks/>
    WITHDRAW,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mrn:stm:schema:port-call-message:0.0.17")]
public partial class LocationStateDepartureLocation {
    
    private Location fromField;
    
    private Location toField;
    
    /// <remarks/>
    public Location from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public Location to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}
